### ISSUE TITLE
Repeated abort/restart on AVD emulators and Extra Keys (EK) overlap

### ISSUE THREAD

**Issue by RalfWerner** [WMCB-Tech/termux-wayland#39] opened 2021-08-20 09:29 UTC
The problem occurs with the _fullscreen selection_ and with EK (the first two choices in preferences - even at **T:X11**).
I've first discovered it in **T:Wayland** (your fork) and checked at eight AVD and two PC's. Unfortunately, the behavior is not the same on all AVD. My first question is: _**Can you do that?**_
> copied from [discussions](https://github.com/suhan-paradkar/termux-wayland/discussions/18#discussioncomment-1162189)

If OTS (termux+X11+Xwayland+Xclient) does _not_ take on the Termux icon with a tap, **1.02.04** can _only_ be started via the X11 icon tap. I did this for different AVD with phones, tablets with Android 10, 11 - _**you too?**_ I have record one of them.

https://user-images.githubusercontent.com/45426380/129156681-938ea751-9862-4d3c-93af-62f082742049.mp4

This does _**not** occur_ on my real devices. Here it flickers and **EK-x** is removes at the End or covered by navigation bar
> customize Ek-x properties for both termux.apk and T: Wayland 

If there is only _one_ **EK** block does not need to be distinguished between **EK-t** and **EK-x**. But that should be _visible_ and _usable_, which is currently not possible in most cases at **EK-x**. My [interest ](https://github.com/suhan-paradkar/termux-wayland/discussions/18#discussioncomment-1157749) question above did not answer so I'll take you to you know the problems. The Configure Event at OS-KB is still missing in 1.02.04 and in many cases OS-KB is not usable together with **EK-x** (covered).
### Addendum: EK Overlap
Six shots of an example with Gboard. The only possibility to enter CTRL+C is the last shot. In all others, EK _or_ OS-KB is possible but _not both._ The device has no Split/PiP function, but _floating_ OS-KB. XClient are here: _touch, check and fluxbox_.
![grafik](https://user-images.githubusercontent.com/45426380/130267497-a2750d95-cc07-4ab5-811b-9c03dd60d585.png)
 For comparison, I have made a shot with VNC, in which EK is always displayed above the OS KB. To position the cursor, the finger must be moved in the narrow strip between blue and transparent. Only here the Touchpad mode is otherwise the mouse mode. 
![grafik](https://user-images.githubusercontent.com/45426380/130268391-fc31e02a-9a3e-4e02-9216-3ae618670591.png)
Each pinch action makes the finger-work even more complicated and floating OS-KB enlarges the unpiched graphics, but shifts the problem to multiple areas - good that there is X11.
My Huawei phone has only _non-floating_, but Split. That does not make the finger-work easier. No shots but the note that I have _**not found**_ any state to use both keyboards at the _**same time**_.The two Xservers can be used simultaneously. An advantage of the OS/VNC EK-KB is the action is completed with _release event_ or previously canceled. That is different in X11 and Termux.
### Compare of the EK from T: X11, Termux and VNC
If, in all cases, the EK of the apps will be displayed in _addition_ to OS-KB non-floating. At **T:X11**, EK is above OS-KB, as in Termux but only in a few cases - see [Split/Pip Video and Discussion](https://github.com/suhan-paradkar/termux-wayland/discussions/19#discussion-3476183). At **T:Wayland** EK is displayed _below_ and nearly always overlapped by OS-KB or Nav-bar - so it's useless. The **Termux** EK is below the _"OS-KB-corrected Termux Window"._ That means above the OS KB.
For VNC`1)` there are several screen additions and VNC-App can not be used as a Split/PiP (shot above). The sweep of EK is different in all three versions and none is _floating_ (my favorite).

`1)` VNC is a lame duck with broken wings. Differentiated: Many events are not supported or intercepted _not_ by XClients, including Configure of the Root Window or Generic (Direct mode). This means the graphics is always in the _init ratio_ of config. I use about 1 to have no big differences when rotate.

**Comment by suhan-paradkar** [comment] 2021-08-20 09:56
> OS-KB is not usable together with EK-x (covered).

Well.. yes.. It's a bug when full-screen mode is enabled and I could reproduce it on my device..

**Comment by RalfWerner** [comment] 2021-08-20 10:16
> So you need an option in preferences to set ek-x??

No! Best solution would be _one_ common (with Termux) **EK** for both Apps and _Configure_ XEvent like in Termux to avoid overlap.
The behavior of this issue is _not_ repeatable on my _real_ devices - _**you too?**_ The other _Choices_ and _Values_ in Preferences, however, are also suspicious `1)` to me and default should be PiP-off and mouse mode to have no problems as possible. 

`1)` A Readme of relevante used-cases would be helful

**Comment by suhan-paradkar** [comment] 2021-08-20 10:27
> Best solution would be one common (with Termux) EK for both Apps and Configure XEvent like in Termux to avoid overlap.

Well.. common EK for both Termux.apk and T: Wayland would be easier only if Extra-keys implementation were moved to termux-shared library instead of remaining in the app...

The bugs with Ek on full-screen mode will be fixed by me soon...

> The behavior of this issue is not repeatable on my real devices

I can't  reproduce overlapping on my real devices too.. and I will fix that too soon... (Both the bugs are at the same place...)

> to me and default should be PiP-off and mouse mode to have no problems as possible.

So PIP mode will be kept to off by default from now on and about mouse mode.... I haven't received any complains about it tho.. only that direct mode has a bug... 

>  A Readme of relevante used-cases would be helful

They are already present in the wiki tab... [here](https://github.com/suhan-paradkar/termux-wayland/wiki/Launching-GUI-applications#known-issues)

**Comment by RalfWerner** [comment] 2021-08-20 17:44
I've extent descriptopn of _EK overlap_ and EK compare by an addendum above (put it later in a detail)!
> I haven't received any complains about it tho.. only that direct mode has a bug

Try to move with five Fingers on the screen for a while and wait until it chrashed! If not, you've luck or have start a XClient, that support Generic events.

> They are already present in the [wiki](https://github.com/suhan-paradkar/termux-wayland/wiki/Launching-GUI-applications#known-issues)

There are explain install and use of Xserver but _not_ the cases where the [Choices](https://github.com/suhan-paradkar/termux-wayland/discussions/18#discussioncomment-1094511) have to set and what it effected.
Also hints, that you with "PiP-R _switch on_" **avoid** the Android-11-[PiP](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-727168733) and Split capability and most XEvents.
I ask, because I've _not found effects_ of someChoices -maybe I've not the proper device?

**Comment by suhan-paradkar** [comment] 2021-09-02 04:09
Closing since this will be fixed upstream

**Closed by suhan-paradkar** 2021-09-02 04:09 UTC
Labels: bug
